config/routes.rb
EmailList::Application.routes.draw do
  resources :recipients, only: [:new, :create, :index]
  root to: "recipients#new"
end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
	attr_accessible :email, :team_id
	belongs_to :team
end

app/models/team.rb
class Team < ActiveRecord::Base
	attr_accessible :name
	has_many :recipients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController

	def index
		@recipients = Recipient.find(:all, :joins => [:team], :order => 'teams.name')
	end

	def new
		@recipient = Recipient.new
	end

	def create
		emails = parse_for_emails_or_phone_numbers(params[:recipient][:email])
		team_id = params[:recipient][:team_id]
		team_name = Team.find(team_id).name

		gb = Gibbon::API.new('a7ae9403bbec1533e0a67c0b46a08a12-us7')
		gb.timeout = 5
		gb.throws_exceptions = false
		list_id = gb.lists.list({:filters => {:list_name => team_name}})["data"].first["id"]
		all_universities_list_id = gb.lists.list({:filters => {:list_name => "All Universities"}})["data"].first["id"]

		emails.each do |email|
			Recipient.find_or_create_by_email(email: email.strip.downcase, team_id: team_id)
			#gb.lists.subscribe({:id => list_id, :email => {:email => email.strip}, :double_optin => false})
			#gb.lists.subscribe({:id => all_universities_list_id, :email => {:email => email.strip}, :double_optin => false})
		end

		redirect_to root_path
	end


	protected
	def parse_for_emails_or_phone_numbers text

  	  if !text
    	return []
  	  end
      #explode string
	  text_array = text.split(
	    /\s*[,;]\s* # comma or semicolon, optionally surrounded by whitespace
	    |           # or
	    \s{1,}      # one or more whitespace characters
	    |           # or
	    [\r\n]+     # any number of newline characters
	    /x)

  	  new_array = []
	  text_array.each do |s|

  		#look at each string
  		s.downcase!
  		s = s.gsub(" ", "")
  		s = s.gsub(",", "")
  		s = s.gsub(";", "")
  		s = s.gsub("+", "")
  		s = s.gsub("-", "")
  		s = s.gsub("(", "")
  		s = s.gsub(")", "")
  		s = s.gsub("[", "")
  		s = s.gsub("]", "")
  		s = s.gsub("#", "")

  		if s =~ /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  			new_array << s
  		elsif s.scan(/<([^<>]*)>/imu).flatten.count > 0
  			email_within = s.scan(/<([^<>]*)>/imu).flatten
  			email_within.each do |ew|
  				if ew =~ /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  					new_array << ew
  				end
  			end
  		end

	  	end

	  	return new_array
	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
	def team_names_and_values
		return_array = []
		Team.all.each do |team|
			return_array << [team.name, team.id]
		end
		return_array.sort
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmailList</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipients/index.html.erb
<h4>All Recipients</h4>
<ul>
	<% @recipients.each do |recipient| %>
		<li><%= recipient.team.name %> ---- <%= recipient.email %></li>
	<% end %>
</ul>

<%= link_to "add new emails", new_recipient_path %>

app/views/recipients/new.html.erb
<%= link_to "see all emails", recipients_path %>

<h4>add emails in comma separated list</h4>

<%= form_for @recipient do |f| %>
	<%= f.text_area(:email, cols: 40, rows: 10) %><br>
	<%= f.select :team_id, team_names_and_values %><br>
	<%= f.submit "Add to Mailchimp Lists" %>
<% end %>